# SPDX-FileCopyrightText: Copyright (c) 2025 Objectionary.com
# SPDX-License-Identifier: MIT

version = 1
[[annotations]]
path = [
    "**.json",
    "**.md",
    "**.txt",
    "**.csv",
    "**.jpg",
    "**.pdf",
    "**.png",
    "**.svg",
    "**.vm",
    "**/.DS_Store",
    "**/.gitignore",
    "**/CNAME",
    ".DS_Store",
    ".gitattributes",
    ".gitignore",
    "README.md",
    "renovate.json",
]
precedence = "override"
SPDX-FileCopyrightText = "Copyright (c) 2025 Objectionary.com"
SPDX-License-Identifier = "MIT"
